In [1]:
import time
import polars as pl
import requests
import json
import pathlib
from typing import List, Tuple
from unipressed import IdMappingClient

In [6]:
gene_id_tsv = "../Data/07_extract_gene/HN5_genelist_rice_2507/HN5_genes_up_rice.tsv"
query_db = "Ensembl_Genomes"
target_db = "UniProtKB"
json_dir = "rice_up_afinfo"
data_url = "cifUrl" # or "pdbUrl", "bcifUrl", "paeImageUrl", "paeDocUrl"
structure_dir = "rice_up_mmcif"
id_mapping_all_file = "rice_up_idmapping_all.tsv"
unmapped_file = "rice_up_unmapped_idmapping.tsv"

&nbsp;

&nbsp;

## 1. UniProt ID mapping step

In [7]:
def chunk_list(lst: List, chunk_size: int) -> List[List]:
    """Split a gene list into chunks"""
    return [lst[i:i + chunk_size] for i in range(0, len(lst), chunk_size)]

In [8]:
def batch_id_mapping(from_db: str, to_db: str, ids: List[str], chunk_size: int = 100) -> Tuple[pl.DataFrame, List[str]]:
    """function for batch id mapping"""
    all_results = []
    all_unmapped = []
    chunked_ids = chunk_list(ids, chunk_size)

    for i, chunk in enumerate(chunked_ids):
        print(f"Processing chunk {i+1}/{len(chunked_ids)}...")
        
        # create request and run
        request = IdMappingClient.submit(source=from_db, dest=to_db, ids=chunk)
        
        # process results
        chunk_results = list(request.each_result())
        mapped_results = [{"from": item["from"], "to": item["to"]} for item in chunk_results]
        all_results.extend(mapped_results)

        # record unmapped ids
        mapped_ids = set(item["from"] for item in mapped_results)
        unmapped = [id for id in chunk if id not in mapped_ids]
        all_unmapped.extend(unmapped)

        # avoid API rate limit
        time.sleep(3)

    # convert results to DataFrame
    final_df = pl.DataFrame(all_results)
    return final_df, all_unmapped

In [10]:
gene_ids = pl.read_csv(
    gene_id_tsv,
    separator='\t'
).get_column("GENEID").to_list()

mapped_df, unmapped_ids = batch_id_mapping(
    query_db,
    target_db,
    gene_ids
)

display(mapped_df)
display(unmapped_ids)

Processing chunk 1/4...
Processing chunk 2/4...
Processing chunk 3/4...
Processing chunk 4/4...

shape: (72, 2)
┌──────────────┬────────┐
│ from         ┆ to     │
│ ---          ┆ ---    │
│ str          ┆ str    │
╞══════════════╪════════╡
│ Os01g0136100 ┆ P27777 │
│ Os03g0245800 ┆ Q10P60 │
│ Os04g0445100 ┆ Q7XUW5 │
│ Os01g0136000 ┆ Q943E7 │
│ Os01g0136200 ┆ Q943E6 │
│ …            ┆ …      │
│ Os08g0544400 ┆ Q8GU82 │
│ Os09g0451500 ┆ Q67UF5 │
│ Os01g0371200 ┆ O65857 │
│ Os07g0644100 ┆ Q8LIB3 │
│ Os07g0246200 ┆ Q9SLY8 │
└──────────────┴────────┘

['Os04g0107900',
 'Os02g0259900',
 'Os02g0259850',
 'Os03g0277300',
 'Os04g0352400',
 'Os01g0136050',
 'Os04g0108101',
 'Os11g0149200',
 'Os01g0184050',
 'Os06g0229000',
 'Os08g0104400',
 'Os11g0533400',
 'Os03g0218500',
 'Os04g0578550',
 'Os05g0296800',
 'Os01g0224200',
 'Os01g0910800',
 'Os06g0668200',
 'Os01g0757500',
 'Os04g0445150',
 'Os03g0745600',
 'Os04g0561500',
 'Os02g0773200',
 'Os03g0133100',
 'Os09g0425200',
 'Os06g0195800',
 'Os09g0109600',
 'Os06g0229066',
 'Os05g0468800',
 'Os01g0918400',
 'Os06g0553100',
 'Os06g0592500',
 'Os04g0548500',
 'Os08g0442900',
 'Os05g0460000',
 'Os03g0832200',
 'Os03g0750100',
 'Os07g0147550',
 'Os03g0724500',
 'Os03g0745000',
 'Os03g0156600',
 'Os03g0701100',
 'Os07g0467200',
 'Os12g0437800',
 'Os01g0585100',
 'Os01g0860601',
 'Os03g0276700',
 'Os02g0668000',
 'Os06g0682900',
 'Os07g0675200',
 'Os01g0124000',
 'Os03g0168100',
 'Os01g0644200',
 'Os03g0300600',
 'Os02g0711300',
 'Os02g0542450',
 'Os03g0230300',
 'Os03g0796000',
 'Os05g0407100',
 'Os05g0494600',
 'Os03g0723400',
 'Os09g0115900',
 'Os04g0538000',
 'Os06g0133500',
 'Os04g0480801',
 'Os05g0375600',
 'Os06g0662550',
 'Os10g0173000',
 'Os02g0824500',
 'Os04g0175400',
 'Os06g0235900',
 'Os11g0506800',
 'Os07g0620700',
 'Os12g0569200',
 'Os06g0110200',
 'Os11g0670900',
 'Os11g0707050',
 'Os02g0546600',
 'Os08g0444440',
 'Os04g0136700',
 'Os09g0494500',
 'Os10g0159033',
 'Os10g0340301',
 'Os10g0390900',
 'Os01g0224300',
 'Os03g0607200',
 'Os03g0286900',
 'Os02g0782550',
 'Os09g0295200',
 'Os01g0840100',
 'Os03g0131800',
 'Os08g0278900',
 'Os06g0356800',
 'Os07g0629500',
 'Os08g0387050',
 'Os10g0373400',
 'Os12g0147200',
 'Os12g0478200',
 'Os03g0271400',
 'Os03g0356498',
 'Os05g0129900',
 'Os07g0633200',
 'Os03g0776900',
 'Os02g0622500',
 'Os03g0113700',
 'Os10g0335000',
 'Os03g0561400',
 'Os03g0822400',
 'Os07g0296000',
 'Os10g0329400',
 'Os01g0719125',
 'Os02g0332450',
 'Os03g0140650',
 'Os07g0418600',
 'Os08g0520600',
 'Os06g0716700',
 'Os10g0462900',
 'Os01g0822900',
 'Os03g0719400',
 'Os11g0147150',
 'Os03g0623100',
 'Os05g0135400',
 'Os05g0457000',
 'Os06g0219500',
 'Os06g0491566',
 'Os08g0506000',
 'Os01g0386500',
 'Os02g0464550',
 'Os06g0159900',
 'Os08g0518800',
 'Os02g0284800',
 'Os03g0267100',
 'Os06g0150400',
 'Os06g0730150',
 'Os07g0549800',
 'Os08g0557800',
 'Os10g0540800',
 'Os11g0707100',
 'Os12g0255850',
 'Os01g0606900',
 'Os02g0463401',
 'Os03g0381300',
 'Os03g0830500',
 'Os04g0167900',
 'Os05g0540300',
 'Os09g0526650',
 'Os01g0327500',
 'Os02g0190100',
 'Os02g0616600',
 'Os09g0515550',
 'Os10g0118800',
 'Os11g0181200',
 'Os11g0303800',
 'Os03g0826900',
 'Os11g0601950',
 'Os03g0293000',
 'Os03g0638400',
 'Os06g0668250',
 'Os09g0272600',
 'Os11g0451700',
 'Os12g0106000',
 'Os03g0727800',
 'Os04g0589800',
 'Os05g0156500',
 'Os05g0200500',
 'Os05g0442400',
 'Os08g0307601',
 'Os08g0546400',
 'Os11g0594500',
 'Os01g0105800',
 'Os01g0594650',
 'Os02g0115950',
 'Os02g0733900',
 'Os02g0630300',
 'Os02g0783700',
 'Os03g0820300',
 'Os04g0415800',
 'Os06g0188950',
 'Os06g0716750',
 'Os09g0474300',
 'Os03g0826800',
 'Os06g0172800',
 'Os06g0698300',
 'Os07g0267200',
 'Os07g0418700',
 'Os10g0537500',
 'Os02g0466400',
 'Os03g0113750',
 'Os03g0718800',
 'Os04g0167875',
 'Os06g0146800',
 'Os06g0198500',
 'Os08g0534350',
 'Os09g0425400',
 'Os11g0601700',
 'Os12g0270900',
 'Os02g0782300',
 'Os04g0150300',
 'Os05g0121750',
 'Os05g0200601',
 'Os05g0223200',
 'Os06g0317100',
 'Os07g0567500',
 'Os08g0117900',
 'Os09g0120033',
 'Os11g0518600',
 'Os04g0402100',
 'Os08g0464000',
 'Os10g0520700',
 'Os01g0719400',
 'Os03g0265600',
 'Os03g0417700',
 'Os05g0151200',
 'Os05g0156401',
 'Os05g0435400',
 'Os08g0500700',
 'Os11g0106700',
 'Os12g0548401',
 'Os01g0124100',
 'Os01g0180800',
 'Os01g0771200',
 'Os01g0849000',
 'Os01g0860450',
 'Os02g0136150',
 'Os03g0263700',
 'Os03g0292900',
 'Os04g0500600',
 'Os06g0726600',
 'Os08g0442200',
 'Os12g0418600',
 'Os12g0548700',
 'Os03g0183500',
 'Os03g0653900',
 'Os03g0822700',
 'Os04g0197350',
 'Os04g0639000',
 'Os05g0579500',
 'Os11g0160400',
 'Os12g0440300',
 'Os01g0524700',
 'Os01g0822800',
 'Os01g0944100',
 'Os02g0164000',
 'Os03g0278800',
 'Os06g0125200',
 'Os09g0491772',
 'Os11g0659200',
 'gene-orf224',
 'Os01g0699400',
 'Os01g0900200',
 'Os02g0134300',
 'Os02g0286933',
 'Os02g0644100',
 'Os03g0277600',
 'Os03g0719450',
 'Os05g0462400',
 'Os06g0593100',
 'Os08g0374701',
 'Os09g0444900',
 'Os10g0334500',
 'Os10g0523900',
 'Os02g0710900',
 'Os03g0244200',
 'Os03g0627900',
 'Os04g0418800',
 'Os05g0373900',
 'Os07g0652900',
 'Os10g0532300',
 'Os12g0600100',
 'Os02g0202700',
 'Os02g0580500',
 'Os02g0629000',
 'Os03g0746900',
 'Os04g0112533',
 'Os04g0280500',
 'Os04g0558200',
 'Os05g0206100',
 'Os05g0367000',
 'Os05g0562300',
 'Os06g0134900',
 'Os07g0561300',
 'Os07g0641700',
 'Os09g0315700',
 'Os01g0160800',
 'Os01g0183300',
 'Os01g0715201',
 'Os03g0296200',
 'Os04g0381600',
 'Os04g0607150',
 'Os05g0460475',
 'Os05g0550300',
 'Os06g0651200',
 'Os08g0374600',
 'Os10g0440500',
 'Os12g0111700']

In [11]:
mapped_df2 = mapped_df.rename(
    {
        "from": "From",
        "to": "UniProt Accession"
    }
)

display(mapped_df2)

shape: (72, 2)
┌──────────────┬───────────────────┐
│ From         ┆ UniProt Accession │
│ ---          ┆ ---               │
│ str          ┆ str               │
╞══════════════╪═══════════════════╡
│ Os01g0136100 ┆ P27777            │
│ Os03g0245800 ┆ Q10P60            │
│ Os04g0445100 ┆ Q7XUW5            │
│ Os01g0136000 ┆ Q943E7            │
│ Os01g0136200 ┆ Q943E6            │
│ …            ┆ …                 │
│ Os08g0544400 ┆ Q8GU82            │
│ Os09g0451500 ┆ Q67UF5            │
│ Os01g0371200 ┆ O65857            │
│ Os07g0644100 ┆ Q8LIB3            │
│ Os07g0246200 ┆ Q9SLY8            │
└──────────────┴───────────────────┘

&nbsp;

&nbsp;

## 2. UniProt re-mapping

In [12]:
def fetch_uniprot_data(ensembl_ids: List[str]) -> pl.DataFrame:
    results = []

    for id in ensembl_ids:
        print(f"Processing {id}...")
        url = (
            f"https://rest.uniprot.org/uniprotkb/search?"
            f"query=gene:{id}&format=json"
        )
        response = requests.get(url)
        
        if response.status_code == 200:
            data = json.loads(response.text)
            for item in data.get('results', []):
                primary_accession = item.get('primaryAccession', '')
                secondary_accessions = item.get('secondaryAccessions', [])
                all_accessions = [primary_accession] + secondary_accessions
                
                for accession in all_accessions:
                    entry = {
                        "From": id,
                        "UniProt Accession": accession
                    }
                    
                    # Check if the accession is a match for the gene 
                    # (e.g. Os03g0293000 matches OrderedLocusNames)
                    match_found = False
                    for gene in item.get('genes', []):
                        for locus in gene.get('orderedLocusNames', []):
                            if locus.get('value', '') == id:
                                match_found = True
                                break
                        if match_found:
                            break
                    
                    if match_found:
                        results.append(entry)
        else:
            print(f"Error fetching data for {id}: {response.status_code}")
        
        time.sleep(5)

    return pl.DataFrame(results)

In [13]:
unmapped_df = fetch_uniprot_data(unmapped_ids)
display(unmapped_df)

Processing Os04g0107900...
Processing Os02g0259900...
Processing Os02g0259850...
Processing Os03g0277300...
Processing Os04g0352400...
Processing Os01g0136050...
Processing Os04g0108101...
Processing Os11g0149200...
Processing Os01g0184050...
Processing Os06g0229000...
Processing Os08g0104400...
Processing Os11g0533400...
Processing Os03g0218500...
Processing Os04g0578550...
Processing Os05g0296800...
Processing Os01g0224200...
Processing Os01g0910800...
Processing Os06g0668200...
Processing Os01g0757500...
Processing Os04g0445150...
Processing Os03g0745600...
Processing Os04g0561500...
Processing Os02g0773200...
Processing Os03g0133100...
Processing Os09g0425200...
Processing Os06g0195800...
Processing Os09g0109600...
Processing Os06g0229066...
Processing Os05g0468800...
Processing Os01g0918400...
Processing Os06g0553100...
Processing Os06g0592500...
Processing Os04g0548500...
Processing Os08g0442900...
Processing Os05g0460000...
Processing Os03g0832200...
Processing Os03g0750100...
Processing Os07g0147550...
Processing Os03g0724500...
Processing Os03g0745000...
Processing Os03g0156600...
Processing Os03g0701100...
Processing Os07g0467200...
Processing Os12g0437800...
Processing Os01g0585100...
Processing Os01g0860601...
Processing Os03g0276700...
Processing Os02g0668000...
Processing Os06g0682900...
Processing Os07g0675200...
Processing Os01g0124000...
Processing Os03g0168100...
Processing Os01g0644200...
Processing Os03g0300600...
Processing Os02g0711300...
Processing Os02g0542450...
Processing Os03g0230300...
Processing Os03g0796000...
Processing Os05g0407100...
Processing Os05g0494600...
Processing Os03g0723400...
Processing Os09g0115900...
Processing Os04g0538000...
Processing Os06g0133500...
Processing Os04g0480801...
Processing Os05g0375600...
Processing Os06g0662550...
Processing Os10g0173000...
Processing Os02g0824500...
Processing Os04g0175400...
Processing Os06g0235900...
Processing Os11g0506800...
Processing Os07g0620700...
Processing Os12g0569200...
Processing Os06g0110200...
Processing Os11g0670900...
Processing Os11g0707050...
Processing Os02g0546600...
Processing Os08g0444440...
Processing Os04g0136700...
Processing Os09g0494500...
Processing Os10g0159033...
Processing Os10g0340301...
Processing Os10g0390900...
Processing Os01g0224300...
Processing Os03g0607200...
Processing Os03g0286900...
Processing Os02g0782550...
Processing Os09g0295200...
Processing Os01g0840100...
Processing Os03g0131800...
Processing Os08g0278900...
Processing Os06g0356800...
Processing Os07g0629500...
Processing Os08g0387050...
Processing Os10g0373400...
Processing Os12g0147200...
Processing Os12g0478200...
Processing Os03g0271400...
Processing Os03g0356498...
Processing Os05g0129900...
Processing Os07g0633200...
Processing Os03g0776900...
Processing Os02g0622500...
Processing Os03g0113700...
Processing Os10g0335000...
Processing Os03g0561400...
Processing Os03g0822400...
Processing Os07g0296000...
Processing Os10g0329400...
Processing Os01g0719125...
Processing Os02g0332450...
Processing Os03g0140650...
Processing Os07g0418600...
Processing Os08g0520600...
Processing Os06g0716700...
Processing Os10g0462900...
Processing Os01g0822900...
Processing Os03g0719400...
Processing Os11g0147150...
Processing Os03g0623100...
Processing Os05g0135400...
Processing Os05g0457000...
Processing Os06g0219500...
Processing Os06g0491566...
Processing Os08g0506000...
Processing Os01g0386500...
Processing Os02g0464550...
Processing Os06g0159900...
Processing Os08g0518800...
Processing Os02g0284800...
Processing Os03g0267100...
Processing Os06g0150400...
Processing Os06g0730150...
Processing Os07g0549800...
Processing Os08g0557800...
Processing Os10g0540800...
Processing Os11g0707100...
Processing Os12g0255850...
Processing Os01g0606900...
Processing Os02g0463401...
Processing Os03g0381300...
Processing Os03g0830500...
Processing Os04g0167900...
Processing Os05g0540300...
Processing Os09g0526650...
Processing Os01g0327500...
Processing Os02g0190100...
Processing Os02g0616600...
Processing Os09g0515550...
Processing Os10g0118800...
Processing Os11g0181200...
Processing Os11g0303800...
Processing Os03g0826900...
Processing Os11g0601950...
Processing Os03g0293000...
Processing Os03g0638400...
Processing Os06g0668250...
Processing Os09g0272600...
Processing Os11g0451700...
Processing Os12g0106000...
Processing Os03g0727800...
Processing Os04g0589800...
Processing Os05g0156500...
Processing Os05g0200500...
Processing Os05g0442400...
Processing Os08g0307601...
Processing Os08g0546400...
Processing Os11g0594500...
Processing Os01g0105800...
Processing Os01g0594650...
Processing Os02g0115950...
Processing Os02g0733900...
Processing Os02g0630300...
Processing Os02g0783700...
Processing Os03g0820300...
Processing Os04g0415800...
Processing Os06g0188950...
Processing Os06g0716750...
Processing Os09g0474300...
Processing Os03g0826800...
Processing Os06g0172800...
Processing Os06g0698300...
Processing Os07g0267200...
Processing Os07g0418700...
Processing Os10g0537500...
Processing Os02g0466400...
Processing Os03g0113750...
Processing Os03g0718800...
Processing Os04g0167875...
Processing Os06g0146800...
Processing Os06g0198500...
Processing Os08g0534350...
Processing Os09g0425400...
Processing Os11g0601700...
Processing Os12g0270900...
Processing Os02g0782300...
Processing Os04g0150300...
Processing Os05g0121750...
Processing Os05g0200601...
Processing Os05g0223200...
Processing Os06g0317100...
Processing Os07g0567500...
Processing Os08g0117900...
Processing Os09g0120033...
Processing Os11g0518600...
Processing Os04g0402100...
Processing Os08g0464000...
Processing Os10g0520700...
Processing Os01g0719400...
Processing Os03g0265600...
Processing Os03g0417700...
Processing Os05g0151200...
Processing Os05g0156401...
Processing Os05g0435400...
Processing Os08g0500700...
Processing Os11g0106700...
Processing Os12g0548401...
Processing Os01g0124100...
Processing Os01g0180800...
Processing Os01g0771200...
Processing Os01g0849000...
Processing Os01g0860450...
Processing Os02g0136150...
Processing Os03g0263700...
Processing Os03g0292900...
Processing Os04g0500600...
Processing Os06g0726600...
Processing Os08g0442200...
Processing Os12g0418600...
Processing Os12g0548700...
Processing Os03g0183500...
Processing Os03g0653900...
Processing Os03g0822700...
Processing Os04g0197350...
Processing Os04g0639000...
Processing Os05g0579500...
Processing Os11g0160400...
Processing Os12g0440300...
Processing Os01g0524700...
Processing Os01g0822800...
Processing Os01g0944100...
Processing Os02g0164000...
Processing Os03g0278800...
Processing Os06g0125200...
Processing Os09g0491772...
Processing Os11g0659200...
Processing gene-orf224...
Processing Os01g0699400...
Processing Os01g0900200...
Processing Os02g0134300...
Processing Os02g0286933...
Processing Os02g0644100...
Processing Os03g0277600...
Processing Os03g0719450...
Processing Os05g0462400...
Processing Os06g0593100...
Processing Os08g0374701...
Processing Os09g0444900...
Processing Os10g0334500...
Processing Os10g0523900...
Processing Os02g0710900...
Processing Os03g0244200...
Processing Os03g0627900...
Processing Os04g0418800...
Processing Os05g0373900...
Processing Os07g0652900...
Processing Os10g0532300...
Processing Os12g0600100...
Processing Os02g0202700...
Processing Os02g0580500...
Processing Os02g0629000...
Processing Os03g0746900...
Processing Os04g0112533...
Processing Os04g0280500...
Processing Os04g0558200...
Processing Os05g0206100...
Processing Os05g0367000...
Processing Os05g0562300...
Processing Os06g0134900...
Processing Os07g0561300...
Processing Os07g0641700...
Processing Os09g0315700...
Processing Os01g0160800...
Processing Os01g0183300...
Processing Os01g0715201...
Processing Os03g0296200...
Processing Os04g0381600...
Processing Os04g0607150...
Processing Os05g0460475...
Processing Os05g0550300...
Processing Os06g0651200...
Processing Os08g0374600...
Processing Os10g0440500...
Processing Os12g0111700...

shape: (697, 2)
┌──────────────┬───────────────────┐
│ From         ┆ UniProt Accession │
│ ---          ┆ ---               │
│ str          ┆ str               │
╞══════════════╪═══════════════════╡
│ Os04g0107900 ┆ A0A0P0W6G9        │
│ Os04g0107900 ┆ A0A0P0W5Z1        │
│ Os04g0107900 ┆ A0A0P0W643        │
│ Os04g0107900 ┆ A0A0P0W604        │
│ Os04g0107900 ┆ C7J151            │
│ …            ┆ …                 │
│ Os08g0374600 ┆ A0A0P0XF07        │
│ Os10g0440500 ┆ A0A0P0XV47        │
│ Os10g0440500 ┆ Q0IXG0            │
│ Os12g0111700 ┆ Q0IQM6            │
│ Os12g0111700 ┆ A0A0P0Y665        │
└──────────────┴───────────────────┘

&nbsp;

&nbsp;

## 3. Concatenate the two dataframes

In [14]:
id_mapping_df = pl.concat(
    [
        mapped_df2,
        unmapped_df
    ],
    how="vertical_relaxed"
).sort(
    by="From",
    descending=False
)

display(id_mapping_df)

shape: (769, 2)
┌──────────────┬───────────────────┐
│ From         ┆ UniProt Accession │
│ ---          ┆ ---               │
│ str          ┆ str               │
╞══════════════╪═══════════════════╡
│ Os01g0105800 ┆ Q657Z2            │
│ Os01g0105800 ┆ B9EYS7            │
│ Os01g0105800 ┆ C7IWH2            │
│ Os01g0105800 ┆ A0A8J8YF34        │
│ Os01g0124000 ┆ Q5ZCB1            │
│ …            ┆ …                 │
│ Os12g0548700 ┆ B9GDL9            │
│ Os12g0548700 ┆ Q2QNZ3            │
│ Os12g0569200 ┆ Q2QND9            │
│ Os12g0600100 ┆ Q0IM43            │
│ Os12g0600100 ┆ Q2QML3            │
└──────────────┴───────────────────┘

In [15]:
id_mapping_df_selected = id_mapping_df.head(10)

display(id_mapping_df_selected)

shape: (10, 2)
┌──────────────┬───────────────────┐
│ From         ┆ UniProt Accession │
│ ---          ┆ ---               │
│ str          ┆ str               │
╞══════════════╪═══════════════════╡
│ Os01g0105800 ┆ Q657Z2            │
│ Os01g0105800 ┆ B9EYS7            │
│ Os01g0105800 ┆ C7IWH2            │
│ Os01g0105800 ┆ A0A8J8YF34        │
│ Os01g0124000 ┆ Q5ZCB1            │
│ Os01g0124000 ┆ A0A0P0UXY0        │
│ Os01g0124000 ┆ Q5ZD53            │
│ Os01g0124100 ┆ A0A0P0UYB2        │
│ Os01g0124100 ┆ Q0JR27            │
│ Os01g0124401 ┆ Q0JR25            │
└──────────────┴───────────────────┘

&nbsp;

&nbsp;

## 4. Get AlphaFold metadata JSON files

In [16]:
def get_af_json(dataframe: pl.DataFrame, target_dir: str):
    """
    Get JSON file from AlphaFoldDB
    """
    pathlib.Path(target_dir).mkdir(parents=True, exist_ok=True)
    
    for row in dataframe.iter_rows():
        gene_id = row[0]
        uniprot_id = row[1]
        
        json_file_name = pathlib.Path(target_dir) / f"{gene_id}_{uniprot_id}_info.json"
        
        if json_file_name.exists():
            message_1 = f"{json_file_name} already exists"
            print(message_1)
            continue
        
        request_url = f"https://alphafold.ebi.ac.uk/api/prediction/{uniprot_id}"
        
        try:
            response = requests.get(request_url, headers={"Accept": "application/json"}, timeout=30)
            response.raise_for_status()
            
            if response.text:
                data = json.loads(response.text) # parse json
                if isinstance(data, list) and len(data) > 0:
                    message_2 = f"AlphaFold ID {uniprot_id} found in AlphaFold"
                    print(message_2)
                    with open(json_file_name, 'w') as f:
                        json.dump(data[0], f, indent=4)
                else:
                    message_3 = f"AlphaFold ID {uniprot_id} not found in AlphaFold"
                    print(message_3)
            else:
                message_4 = f"Empty response for AlphaFold ID {uniprot_id}"
                print(message_4)
        except requests.exceptions.RequestException as e:
            message_5 = f"Request failed: {e}"
            print(message_5)
            message_6 = f"AlphaFold ID {uniprot_id} not found in AlphaFold"
            print(message_6)
        time.sleep(5)

In [17]:
get_af_json(id_mapping_df_selected, json_dir)

Request failed: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/api/prediction/Q657Z2
AlphaFold ID Q657Z2 not found in AlphaFold
Request failed: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/api/prediction/B9EYS7
AlphaFold ID B9EYS7 not found in AlphaFold
Request failed: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/api/prediction/C7IWH2
AlphaFold ID C7IWH2 not found in AlphaFold
Request failed: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/api/prediction/A0A8J8YF34
AlphaFold ID A0A8J8YF34 not found in AlphaFold
AlphaFold ID Q5ZCB1 found in AlphaFold
Request failed: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/api/prediction/A0A0P0UXY0
AlphaFold ID A0A0P0UXY0 not found in AlphaFold
AlphaFold ID Q5ZD53 found in AlphaFold
Request failed: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/api/prediction/A0A0P0UYB2
AlphaFold ID A0A0P0UYB2 not found in AlphaFold
AlphaFold ID Q0JR27 found in AlphaFold
AlphaFold ID Q0JR25 found in AlphaFold

&nbsp;

&nbsp;

## 5. Download CIF files

In [18]:
def get_cif_file(json_dir_path: str, output_dir_path: str):
    """
    Get CIF file from JSON files retrieved from AlphaFoldDB
    
    Args:
        json_dir_path: Directory containing AlphaFold JSON metadata files
        output_dir_path: Directory to save downloaded CIF files
    """
    pathlib.Path(output_dir_path).mkdir(parents=True, exist_ok=True)

    for json_file in pathlib.Path(json_dir_path).glob("*.json"):
        with open(json_file, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
                cif_url = data.get(data_url)
                
                if not cif_url:
                    print(f"No {data_url} found in {json_file}")
                    continue
                    
                # Extract filename from URL and create output path
                cif_filename = pathlib.Path(cif_url).name
                output_file = pathlib.Path(output_dir_path) / cif_filename
                
                # Skip if file already exists
                if output_file.exists():
                    print(f"{output_file} already exists")
                    continue
                
                print(f"Downloading {cif_url}")
                response = requests.get(cif_url, timeout=30)
                response.raise_for_status()
                
                # Save CIF file
                output_file.write_bytes(response.content)
                print(f"Saved {output_file}")
                
            except json.JSONDecodeError:
                print(f"Error parsing JSON file: {json_file}")
            except requests.exceptions.RequestException as e:
                print(f"Error downloading CIF file: {e}")
            
            # Rate limiting
            time.sleep(1)

In [19]:
get_cif_file(json_dir, structure_dir)

Downloading https://alphafold.ebi.ac.uk/files/AF-Q5ZD53-F1-model_v6.cif
Saved rice_up_mmcif/AF-Q5ZD53-F1-model_v6.cif
Downloading https://alphafold.ebi.ac.uk/files/AF-Q0JR27-F1-model_v6.cif
Saved rice_up_mmcif/AF-Q0JR27-F1-model_v6.cif
Downloading https://alphafold.ebi.ac.uk/files/AF-Q5ZCB1-F1-model_v6.cif
Saved rice_up_mmcif/AF-Q5ZCB1-F1-model_v6.cif
Downloading https://alphafold.ebi.ac.uk/files/AF-Q0JR25-F1-model_v6.cif
Saved rice_up_mmcif/AF-Q0JR25-F1-model_v6.cif

&nbsp;

&nbsp;

## 6. Save all results

In [14]:
unmapped_df.write_csv(unmapped_file, separator="\t")
id_mapping_df.write_csv(id_mapping_all_file, separator="\t")